### ISSUE TITLE
THANKS FOR ASKING FIRST

### ISSUE THREAD

**Issue by danielb7390** [trumad/PS2ArtworkDownloader#1]
OPLM Database can be downloaded from
http://www.ps2-home.com/forum/viewtopic.php?f=64&t=6734

---ORIGINAL POST---
Hi
oplmanager dev here.
Are you really hitting my service without asking?! WTF men?
And you are not even downloading one game ART at a time, you are downloading entire pages! Do you even know how much load on the server this can put if people start to use this?!?!

**Comment by trumad** [comment]
Hello. You seem annoyed. Why?

I did ask first. I opened a forum thread on ps2-home called "full oplm art collection" requesting the full collection of art. The topic was disapproved by the moderator. I believe that's you?

I am not currently hitting your service. Its excellent by the way. It really makes it easy to have a tidy collection of isos & artwork. 

Since you are not sharing a full collection of art, but rather obfuscating image urls & using your software to gatekeep the artwork, this tool is necessary in order to effectively archive the art and allow the full collection to exist outside of tha hands of one person - a single point of failure. Please consider sharing a full collection so it can be archived in a more open way in the event of your service terminating for some reason. This will have the added benefit of taking load off your server.

I did try reaching out via my forum thread. Please consider allowing dialogue next time. Peace.

**Comment by danielb7390** [comment]
Well, you are wrong I'm not a moderator. You could have sent me a private message in ps2-home. Or contact me on Facebook.
How you are not hitting my service?! You are batch downloading entire pages! That's a lot of requests in a row!
I'm not obfuscating image urls, they are the image md5 since a image can be in multiple games! Like screenshots, icons etc.

I do understand your point in downloading the entire DB, but for that it would be required to have at least a monthly/weekly/daily zip of it. That would be probably a few GB, since it would have lots of duplicate files because of what i explained above

**Comment by trumad** [comment]
My bad - the forums are quite confusing and not easy to parse for an outsider. At the top of the OPLM forum it says "Moderator: danielb". I guess that means you are not the same danielb or that this text on the forum does not actually mean you are a moderator. As I say, the forums are confusing. Also I don't use Facebook. Opening a thread on the OPLM forum was sufficient for me - I am sorry that you feel it was not sufficient for you. I'm glad we're discussing it now.

I am not currently hitting your service in the present tense. It is a lot of requests in a row, but the script is designed to run single-threaded. It will not make your server fall over. It waits for the last image to fully download before getting another one. But all that is irrelevant now because I see you have removed the game list pages from your site. The script is now broken and your full collection of artwork now cannot be downloaded by everyone, as before.

That's quite clever with the MD5 hashes. But still, it is not possible for a user to easily browse around the files section and grab as much as they want.

I understand you want the artwork to be up to date - we all do. But in the unlikely event that you die or the server suddenly disappears, we are left without artwork. Having an out of date collection (which seems to already include all the most popular games anyway) is better than losing access completely. 

You're right - the full collection is quite large when files are downloaded as duplicates - 2.87 GB. I would recommend uploading it to the internet archive. You could even automate this on your server using this python library: https://internetarchive.readthedocs.io/en/latest/quickstart.html#uploading . This way your work can be preserved well into the future. What do you think?

**Comment by danielb7390** [comment]
Oh, ok im moderator in that subforum i guess. But i didn't delete your post.
I will need to look into some sort of full DB zip. I was thinking maybe a monthly torrent? That would split the bandwidth if people seed, and a lot of copies would exist.
I'm not sure about the internetarchive, they might consider the art piracy?!

**Comment by trumad** [comment]
Thank you for engaging with the idea of archiving the files. 

I would say that nobody will bother seeding torrents. Even if they do, the torrent will die after a few years - especially if the content changes every month and people need to redownload the new torrent. It would definitely be good to keep the load off your server though, if it is a major concern. I honestly think that's where Internet Archive comes in.

Internet Archive will remove pirated content on request. I don't think it will be a major concern for this project. IA are friendly to videogame content, in my experience. You can already play the full collection of roms for many systems right in your browser, for example. ( https://archive.org/details/consolelivingroom).

I firmly believe that the internet archive is the best service for this. They have torrent links also, and the artwork can be expected to stay available with them pretty much forever. That site will not go anywhere. You could link to there from your main page for anyone who wants the full collection.

Again, thank you for engaging with the idea of archiving the files. They are immensely important - you've done an important thing in collecting them. I'm just so worried at the thought of only one person/service having full access to all the artwork, because it's so valuable to PS2 gamers. The more it can be shared, the safer it is.

**Comment by danielb7390** [comment]
Hey, you are starting to really annoy me!
"fixed a bug where the owner of OPL Manager removed the gamelist" is this a joke right?

I'm still looking into the backup option. I actually was looking at the python upload script this morning. If your problem was backup i see you already uploaded this month database to internet archive, so i don't see the point in keeping this up!

**Comment by danielb7390** [comment]
Database backup working and uploaded.
http://www.ps2-home.com/forum/viewtopic.php?f=64&t=6734
https://archive.org/details/OPLM_ART_2018_11

**Comment by trumad** [comment]
Apologies for the delay in response - there are lots of real life things going on right now.

That's incredible - thank you very much for that. I'm happy to know that there is a full collection available online now. Thank you for the work you've put in to scheduling an upload to the internet archive. Your work in building this collection is important, and it's so great to see it mirrored elsewhere and being archived safely.

I'm sorry for the frustration I clearly caused you. I have removed all content from the JS file and the readme and I see no reason to continue with this project going forward. I hope that goes some way to repairing things. I wish you all the best with the continuation of your project.

**Comment by danielb7390** [comment]
Thanks!
